version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      appnetwork:
        ipv4_address: 172.30.0.6
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      appnetwork:
        ipv4_address: 172.30.0.5

  receiver:
    build: ./receiver
    ports:
      - "8080:8080"
    networks:
      appnetwork:
        ipv4_address: 172.30.0.10

  storage:
    build: ./storage
    ports:
      - "8090:8090"
    depends_on:
      - "receiver"
    networks:
      appnetwork:
        ipv4_address: 172.30.0.9

  processing:
    build: ./processing
    ports:
      - "8100:8100"
    depends_on:
      - "storage"
    networks:
      appnetwork:
        ipv4_address: 172.30.0.8

  health:
    build: ./health
    ports:
      - "8110:8110"
    networks:
      appnetwork:
        ipv4_address: 172.30.0.7

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: events
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      appnetwork:
        ipv4_address: 172.30.0.6

networks:
  appnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

volumes:
  mysql-data:
