version: '2'
services:
  receiver:
    image: receiver
    ports:
    - "8080:8080"
    networks:
      appnetwork:
        ipv4_address: 172.30.0.10

  storage:
    image: storage
    ports:
    - "8090:8090"
    depends_on:
    - "receiver"
    networks:
      appnetwork:
        ipv4_address: 172.30.0.9

  processing:
    image: processing
    ports:
    - "8100:8100"
    depends_on:
    - "storage"
    networks:
      appnetwork:
        ipv4_address: 172.30.0.8

networks:
  appnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1